apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: usersvc
  name: usersvc
spec:
  type: ClusterIP
  ports:
  - name: usersvc
    port: 80
  selector:
    app: usersvc
